### ISSUE TITLE
Failure to build because of missing dependecy

### ISSUE THREAD

**Issue by aeldemery** [misterdanb/shady#117]
I've failed to build `shady` because meson complains of missing `c++` dependency

```
src/meson.build:88:0: ERROR: C++ shared or static library 'HLSL' not found
```
If you could add entry in the `README.md` listing required dependencies and how to install/get them.

Thanks

**Comment by Ninja-Koala** [comment]
I added dependency installation instruction for different linux distributions.
I think that should fix this issue.
Thank's for your feedback!
