### ISSUE TITLE
Shadertoy search not loading when there is a second window with search open

### ISSUE THREAD

**Issue by Ninja-Koala** [misterdanb/shady#82]
Closing the search in the second window causes the search to finish nearly immediately.

**Comment by heyjuvi** [comment]
It is not clear to me, what the error scenario looks like and I am not able to reproduce any error. Can you please provide more information on how to trigger the bug?

**Comment by Ninja-Koala** [comment]
My steps to reproduce:
1. Open Shady
2. Edit default shader and recompile
3. open new window
4. open search and enter search term in window 2
5. when the search window 2 is fully loaded, open search in window1 and enter search term
6. wait indefinitely
7. close search in window 2 and watch the search in window 1 finish immediately
